backend/translations/urls.py
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r"persons", views.PersonViewSet, basename="person")
router.register(r"languages", views.LanguageViewSet, basename="language")
router.register(r"texts", views.SourceTextViewSet, basename="text")
router.register(r"volumes", views.VolumeViewSet, basename="volume")
router.register(r"volume-releases", views.VolumeReleaseViewSet, basename="volume-release")
router.register(r"publishers", views.PublisherViewSet, basename="publisher")
router.register(r"series", views.SeriesViewSet, basename="series")
router.register(r"features", views.FeatureViewSet, basename="feature")
router.register(r"reviews", views.ReviewViewSet, basename="review")
router.register(
    r"published-reviews", views.PublishedReviewViewSet, basename="published-review"
)
router.register(r"links", views.LinkViewSet, basename="link")
router.register(
    r"alternate-names", views.AlternateNameViewSet, basename="alternate-name"
)


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("graphql", GraphQLView.as_view(graphiql=True)),
    path("api/graphql", csrf_exempt(GraphQLView.as_view(graphiql=False))),
    path("about/", views.AboutView.as_view(), name="about"),
    path("texts/", views.SourceTextIndexView.as_view(), name="source_text_index"),
    path("authors/", views.AuthorIndexView.as_view(), name="author_index"),
    path("translators/", views.TranslatorIndexView.as_view(), name="translator_index"),
    path(
        "texts/<int:pk>/",
        views.SourceTextDetailView.as_view(),
        name="source_text_detail",
    ),
    path(
        "texts/<int:pk>/translations/",
        views.TranslationComparisonsView.as_view(),
        name="translation_compare",
    ),
    path("persons/<int:pk>/", views.PersonDetailView.as_view(), name="person_detail"),
    path("users/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path(
        "published-reviews/<int:pk>/",
        views.PublishedReviewDetailView.as_view(),
        name="published_review_detail",
    ),
    path("volumes/<int:pk>/", views.VolumeDetailView.as_view(), name="volume_detail"),
    path(
        "volumes/<int:vol>/reviews/",
        views.ReviewIndexView.as_view(),
        name="review_list",
    ),
    path(
        "volumes/<int:vol>/published-reviews/",
        views.PublishedReviewIndexView.as_view(),
        name="publishedreview_list",
    ),
    path(
        "volumes/<int:vol>/published-reviews/add/",
        views.PublishedReviewLWCView.as_view(),
        name="publishedreview_add",
    ),
    path(
        "volumes/add/",
        views.VolumeLWCView.as_view(),
        name="volume_add",
    ),
    path(
        "volumes/<int:vol>/review/",
        views.ReviewCreateView.as_view(),
        name="review_create",
    ),
    path(
        "reviews/<int:pk>/",
        views.UserReviewDetailView.as_view(),
        name="user_review_detail",
    ),
    path(
        "reviews/<int:pk>/update/",
        views.ReviewUpdateView.as_view(),
        name="review_update",
    ),
    path(
        "reviews/<int:pk>/delete/",
        views.ReviewDeleteView.as_view(),
        name="review_delete",
    ),
    path(
        "publishers/<int:pk>/",
        views.PublisherDetailView.as_view(),
        name="publisher_detail",
    ),
    path("series/<int:pk>/", views.SeriesDetailView.as_view(), name="series_detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("submit/", views.UserSubmissionCreateView.as_view(), name="submit"),
    path("api/", include(router.urls)),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("translations.urls")),
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/translations/models.py
import urllib.parse

import requests
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from config import settings

FORMAT_CHOICES = [("PR", "Prose"), ("VR", "Verse")]


class AuthorNameMixin:
    def author_string(self):
        authors = list(self.persons.all())
        if len(authors) < 3:
            return " and ".join(str(a) for a in authors)
        else:
            first = ", ".join(str(a) for a in authors[:-1])
            last = str(authors[-1])
            return f"{first}, and {last}"


class UserCreatedMixin(models.Model):
    class Meta:
        abstract = True

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True
    )
    date_created = models.DateTimeField(auto_now_add=True)


class UserCreatedApprovalMixin(UserCreatedMixin):
    class Meta:
        abstract = True

    approved = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.user and self.user.is_superuser:
            self.approved = True

        super().save(*args, **kwargs)


class Link(models.Model):
    class Meta:
        ordering = ["resource_type"]

    RESOURCE_TYPE_CHOICES = [
        ("CO", "Get a Copy"),
        ("FT", "Full Text"),
        ("WS", "Website"),
        ("BO", "Bio"),
        ("RS", "Resources"),
    ]

    parent_relationship = "content_object"

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    link = models.URLField()
    source = models.CharField(max_length=255)
    resource_type = models.TextField(choices=RESOURCE_TYPE_CHOICES)

    def __str__(self):
        return f"Link {self.link}"


class AlternateName(models.Model):
    ALTERNATE_NAME_TYPE_CHOICES = [
        ("OR", "Original Language Name"),
        ("TL", "Transliterated Original Language Name"),
        ("TR", "Alternate Name Translation"),
        ("NM", "Alternate Name"),
    ]
    parent_relationship = "content_object"

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    name = models.CharField(max_length=255, blank=False, null=False)
    alternate_name_type = models.CharField(
        max_length=2, choices=ALTERNATE_NAME_TYPE_CHOICES
    )

    def __str__(self):
        return f"Alternate Name {self.name}"


class Language(models.Model):
    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Person(UserCreatedApprovalMixin):
    class Meta:
        ordering = ["sort_name"]

    first_name = models.CharField(max_length=255, blank=True)
    middle_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    sole_name = models.CharField(max_length=255, blank=True)
    sort_name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True)
    links = GenericRelation(Link)
    alternate_names = GenericRelation(AlternateName)

    def save(self, *args, **kwargs):
        self.sort_name = (
            self.sole_name
            if self.sole_name
            else f"{self.last_name}, {self.first_name} {self.middle_name}".strip()
        )
        super().save(*args, **kwargs)

    def clean(self):
        if (not self.sole_name and (not self.first_name or not self.last_name)) or (
            self.sole_name and (self.first_name or self.middle_name or self.last_name)
        ):
            raise ValidationError(
                _(
                    "Populate either the Sole Name or the First Name"
                    "and Last Name fields"
                )
            )

    def full_name(self):
        if self.sole_name:
            return self.sole_name

        if self.middle_name:
            return f"{self.first_name} {self.middle_name} {self.last_name}"

        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.sort_name

    def translation_count(self):
        return self.features.filter(feature="TR").count()

    def get_absolute_url(self):
        return reverse("person_detail", args=[str(self.id)])


class SourceTextManager(models.Manager["SourceText"]):
    def get_queryset(self) -> models.QuerySet["SourceText"]:
        return super().get_queryset().select_related("author")


class SourceText(UserCreatedApprovalMixin):
    class Meta:
        ordering = ["title"]

    objects = SourceTextManager()

    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        Person, related_name="source_texts", on_delete=models.PROTECT
    )
    language = models.ForeignKey(
        Language, related_name="source_texts", on_delete=models.PROTECT
    )
    format = models.TextField(choices=FORMAT_CHOICES)
    date = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)

    # Sample passage data
    sample_passage = models.TextField(blank=True)
    sample_passage_spec = models.CharField(max_length=255, blank=True)
    sample_passage_source = models.CharField(max_length=255, blank=True)
    sample_passage_source_link = models.URLField(blank=True, null=True)
    sample_passage_license = models.CharField(max_length=255, blank=True)
    sample_passage_license_link = models.URLField(blank=True, null=True)

    # Coverage tracking
    coverage = models.TextField(blank=True)
    coverage_date = models.DateField(blank=True, null=True)

    # Generic relations
    links = GenericRelation(Link)
    alternate_names = GenericRelation(AlternateName)

    def display_name(self):
        return f"{self.title} ({self.author})"

    def __str__(self):
        return self.display_name()

    def get_absolute_url(self):
        return reverse("source_text_detail", args=[str(self.id)])

    def get_original_language_title(self):
        olt = self.alternate_names.filter(alternate_name_type="OR")

        if olt:
            return olt[0].name


class Publisher(UserCreatedApprovalMixin):
    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    links = GenericRelation(Link)

    def __str__(self):
        return self.name


class Series(UserCreatedApprovalMixin):
    class Meta:
        verbose_name_plural = "series"
        ordering = ["name"]

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class VolumeManager(models.Manager["Volume"]):
    def get_queryset(self) -> models.QuerySet["Volume"]:
        return super().get_queryset().prefetch_related("features", "series", "publisher", "features__source_text", "features__language", "features__persons")


class Volume(UserCreatedApprovalMixin):
    class Meta:
        ordering = ["title"]

    objects = VolumeManager()

    title = models.CharField(max_length=255)
    published_date = models.DateField(blank=True)
    publisher = models.ForeignKey(
        Publisher, related_name="volumes", on_delete=models.PROTECT
    )
    series = models.ForeignKey(
        Series, related_name="volumes", on_delete=models.PROTECT, null=True, blank=True
    )
    isbn = models.CharField(max_length=32, blank=True)
    oclc_number = models.CharField(max_length=32, blank=True)
    links = GenericRelation(Link)
    description = models.TextField(blank=True)

    # Additional features

    feature_maps = models.BooleanField(default=False)
    feature_index = models.BooleanField(default=False)
    feature_bibliography = models.BooleanField(default=False)
    feature_glossary = models.BooleanField(default=False)

    def __str__(self):
        if self.published_date:
            return f"{self.title} ({self.publisher}, {self.published_date.year})"

        return f"{self.title} ({self.publisher})"

    def get_general_features(self):
        return Feature.objects.filter(volume=self, source_text=None)

    def translations(self):
        return self.features.filter(feature="TR")

    def get_absolute_url(self):
        return reverse("volume_detail", args=[str(self.id)])

    def oclc_link(self):
        if self.oclc_number:
            escaped = urllib.parse.quote(self.oclc_number)
            return f"https://www.worldcat.org/oclc/{escaped}"
        elif self.isbn:
            escaped = urllib.parse.quote(self.isbn)
            return (
                f"https://www.worldcat.org/search?q=bn%3A{escaped}"
                "&qt=advanced&dblist=638"
            )

    def bookshop_link(self):
        if self.isbn:
            escaped = urllib.parse.quote(self.isbn)
            return f"https://bookshop.org/a/15029/{escaped}"

    def update_automatic_links(self):
        links = self.links.all()[:]

        # Do we need an OCLC link?
        url = self.oclc_link()
        if (
            url
            and not any(
                this_link.link.startswith("https://www.worldcat.org")
                for this_link in links
            )
            and requests.head(url).status_code < 300
        ):
            oclc = Link(
                content_object=self,
                link=self.oclc_link(),
                source="Worldcat Libraries",
                resource_type="CO",
            )
            oclc.save()

        url = self.bookshop_link()
        if (
            url
            and not any(
                this_link.link.startswith("https://bookshop.org") for this_link in links
            )
            and requests.head(url).status_code < 300
        ):
            bookshop = Link(

backend/translations/templates/translations/about.html
{% extends "base.html" %}

{% block title %}
Bibliothekai
{% endblock %}

{% block content %}
<h1 class="mt-4 mb-4">Bibliothekai</h1>
<h2>Mission</h2>
<p>
    Our mission is to provide a comprehensive resource on the best translations of classical texts into modern languages. We want to help students, teachers, and interested readers everywhere access Greek and Roman literature, history, and philosophy through accurate, accessible, and up-to-date translations into English and other modern languages.
</p>
<p>
    We welcome classical enthusiasts to join our efforts by contributing information about more translations and by writing reviews to help the community understand the qualities of different translations.
</p>
<h2>
    Roadmap
</h2>
<p>
    We're excited to make Bibliothekai better and better. Our top priorities include:
    <ul>
        <li>Making it easier to filter and compare available translations.</li>
        <li>Opening more areas for user contribution.</li>
        <li>Adding publisher catalogs in bulk.</li>
    </ul>
</p>
<h2>
    Technology
</h2>
<p>
    Bibliothekai is built with Django, Bootstrap, and the open source Lightning Web Components framework.
</p>
<h2>
    Privacy, Cookies, and Affiliate Links
</h2>
<p>
    Bibliothekai uses cookies only to allow you to log in. We don't use tracking cookies or any other type of cookies. We don't record any information about you except for content that you create on the site and any details you choose to share when you create your account, such as your preferred display name, email address, and profile, if any. If you'd like information about you removed from our site, please reach out to <a href="mailto:david@ktema.org">David Reed</a>.
</p>
<p>
    We do not use any third-party analytics. We do not display ads.
</p>
<p>
    Your service providers and ours (including Cloudflare and Heroku) may collect additional information.
</p>
<p>
    Links to booksellers may include an affiliate code and result in a small commission to this site. If you choose to navigate to a bookseller or another third-party link from Bibliothekai, the privacy policy of the third party is in effect.
</p>

{% endblock %}

backend/translations/templates/translations/person_detail.html
{% extends "base.html" %}

{% block title %}
{{ person.full_name }}
{% endblock %}

{% block content %}
{% if user.is_superuser %}
<div class="float-right">
    <small>
        <a href="{% url 'admin:translations_person_change' person.id %}">View on Admin</a>
    </small>
</div>
{% endif %}
<h1 class="mt-4 mb-4">{{ person.full_name }}</h1>
<p>
    {{ person.description|linebreaks }}
</p>
{% if person.alternate_names.count %}
<p>
    Also known as
    {% if person.alternate_names.count > 1 %}
<ul>
    {% for a in person.alternate_names.all %}
    <li>
        {{ a.name }}
    </li>
    {% endfor %}
</ul>
{% else %}
{% for a in person.alternate_names.all %}
{{ a.name }}.
{% endfor %}
{% endif %}
</p>
{% endif %}
{% if sourcetexts.count %}

<h2 class="mt-4">Texts</h2>
{% for s in sourcetexts %}
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title clearfix">
            {{ s.title }}
            {% if s.get_original_language_title and s.title != s.get_original_language_title %}
            ({{ s.get_original_language_title }})
            {% endif %}
            <a class="float-right btn btn-sm btn-outline-primary" href="{% url 'source_text_detail' s.id %}">
                View translations
            </a>
        </h5>
        <div class="card-text">
            <p>{{ s.language }} {{ s.get_format_display|lower }}. {{ s.date }}</p>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

{% if translations %}
<h2 class="mt-4">Translations</h2>
{% for f in translations %}
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">
            <a href="{% url 'person_detail' f.source_text.author.id %}">{{ f.source_text.author.full_name }}</a>,
            <cite><a href="{% url 'source_text_detail' f.source_text.id %}">{{ f.source_text.title }}</a></cite>
        </h5>
        <div class="card-text">
            <p>
                Translation into {{ f.language }} {{ f.get_format_display|lower }}.
            </p>
            <p>Published in <a href="{% url 'volume_detail' f.volume.id %}">{{ f.volume.title }}</a>
                ({{f.volume.publisher }}{% if vol.published_date %}, {{ f.volume.published_date.year }}{% endif%})
            </p>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

{% if publishedreviews %}
<h2 class="mt-4">Published Reviews</h2>
{% for r in publishedreviews %}
{% include "components/published_review.html" with review=r include_volume=True %}
{% endfor %}
{% endif %}

{% include "components/links_component.html" with links=person.links.all %}

{% endblock %}

backend/translations/templates/translations/published_review_detail.html
{% extends "base.html" %}

{% block title %}
{% if publishedreview.title %} {{ publishedreview.title }} {% else %} Review {% endif %}
{% endblock %}

{% block content %}
{% if user.is_superuser %}
<div class="float-right">
    <small>
        <a href="{% url 'admin:translations_publishedreview_change' publishedreview.id %}">View on Admin</a>
    </small>
</div>
{% endif %}

<h1 class="mt-4 mb-4">Published Review</h1>
{% include "components/published_review.html" with review=publishedreview include_volume=True %}
{% endblock %}

backend/translations/templates/translations/source_text_detail.html
{% extends "base.html" %}
{% load comma_lists %}
{% load manifest %}

{% block title %}
{{ sourcetext.title }}
{% endblock %}

{% block content %}
{% if user.is_superuser %}
<div class="float-right">
    <small>
        <a href="{% url 'admin:translations_sourcetext_change' sourcetext.id %}">View on Admin</a>
    </small>
</div>
{% endif %}

<h1 class="mt-4 mb-4">
    {{ sourcetext.title }}
</h1>
<div class="card-deck">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Author</h5>
            <div class="card-text clearfix">
                {{ sourcetext.author.full_name }}
                <div class="float-right">
                    <a class="ml-3 btn btn-outline-secondary btn-sm"
                        href="{% url 'person_detail' sourcetext.author.id %}">
                        More
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% if sourcetext.alternate_names.count %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Other Titles</h5>
            {% if sourcetext.alternate_names.count > 1 %}
            <ul class="list-group list-group-flush">
                {% for a in sourcetext.alternate_names.all %}
                <li class="list-group-item">
                    {{ a.name }}
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <div class="card-text">
                {% for a in sourcetext.alternate_names.all %}
                {{ a.name }}
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
    {% endif %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Original Language</h5>
            <div class="card-text">
                {{ sourcetext.language }}
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Format</h5>
            <div class="card-text">
                {{ sourcetext.get_format_display }}
            </div>
        </div>
    </div>
    {% if sourcetext.date %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Date</h5>
            <div class="card-text">
                {{ sourcetext.date }}
            </div>
        </div>
    </div>
    {% endif %}
</div>

{% if sourcetext.description %}
<h2 class="mt-4">Description</h2>
<p>
    {{ sourcetext.description|linebreaks }}
</p>
{% endif %}

{% if sourcetext.coverage %}
<h2 class="mt-4">Coverage</h2>
<p>
    {{ sourcetext.coverage|linebreaks }}
</p>
{% endif %}


<div id="lwc"></div>

{% manifest_match '*translationView*.js' '<script src="{match}"></script>' %}

{% include "components/links_component.html" with links=sourcetext.links.all %}

{% endblock %}

backend/translations/templates/translations/volume_detail.html
{% extends "base.html" %}
{% load comma_lists %}
{% block title %}
{{ volume.title }}
{% endblock %}

{% block content %}
{% if user.is_superuser %}
<div class="float-right">
    <small>
        <a href="{% url 'admin:translations_volume_change' volume.id %}">View on Admin</a>
    </small>
</div>
{% endif %}

<h1 class="mt-4 mb-4">{{ volume.title }}</h1>

<div class="row">
    <div class="col-sm-2">
        <h5>Catalog Details</h5>
    </div>
    <div class="col">
        {% pill "Publisher" volume.publisher "publisher_detail" volume.publisher.id %}
        {% if volume.series %}
        {% pill "Series" volume.series "series_detail" volume.series.id %}
        {% endif %}
        {% for release in volume.releases.all %}
        {% if release.release_type %}
        {% pill "Type" release.get_release_type_display %}
        {% endif %}
        {% if release.published_date %}
        {% pill "Date" release.published_date.year %}
        {% endif %}
        {% if release.isbn %}
        {% pill "ISBN" release.isbn %}
        {% endif %}
        {% endfor %}
    </div>
</div>
<hr>

{% if volume.description %}
<div class="row">
    <div class="col-sm-2">
        <h5>Description</h5>
    </div>
    <div class="col">
        {{ volume.description|linebreaks }}
    </div>
</div>
<hr>

{% endif %}

{% if volume.feature_glossary or volume.feature_index or volume.feature_bibliography or volume.feature_maps or volume.get_general_features.count %}
<div class="row">
    <div class="col-sm-2">
        <h5>Resources</h5>
    </div>
    <div class="col">
        {% if volume.get_general_features.count %}
        {% for f in volume.get_general_features %}
        {% if f.feature == "IN" %}
        <span class="badge badge-pill badge-primary">
            {{ f.get_feature_display }}
        </span>
        {% endif %}
        {% if f.feature == "ED" %}
        <span class="badge badge-pill badge-danger">
            {{ f.get_feature_display }}
        </span>
        {% endif %}
        {% if f.feature == "NT" %}
        <span class="badge badge-pill badge-warning">
            {{ f.get_feature_display }}
        </span>
        {% endif %}
        {% if f.feature == "CM" %}
        <span class="badge badge-pill badge-success">
            {{ f.get_feature_display }}
        </span>
        {% endif %}
        by
        {% commalist f.persons.all %}
        <a href="{% url 'person_detail' item.id %}">{{ item.full_name }}</a>
        {% endcommalist %}
        <br>
        {% endfor %}
        {% endif %}
        {% if volume.feature_glossary %}
        <span class="badge badge-pill badge-info">Glossary</span>
        {% endif %}
        {% if volume.feature_index %}
        <span class="badge badge-pill badge-secondary">Index</span>
        {% endif %}
        {% if volume.feature_bibliography %}
        <span class="badge badge-pill badge-dark">Bibliography</span>
        {% endif %}
        {% if volume.feature_maps %}
        <span class="badge badge-pill badge-success">Maps</span>
        {% endif %}
    </div>
</div>
<hr>
{% endif %}


{% regroup features by source_text as texts %}

<h2>Translations</h2>
{% for t in texts %}
{% if t.grouper.id %}
{% regroup t.list by author_string as grouped_features %}
<div class="card-deck">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title clearfix">
                {{ t.grouper.title }} {% if t.grouper.get_original_language_title and t.grouper.get_original_language_title != t.grouper.title %}
                ({{ t.grouper.get_original_language_title }}){% endif %}
                <a href="{% url 'source_text_detail' t.grouper.id %}"
                    class="float-right btn btn-outline-secondary btn-sm">
                    More translations
                </a>
            </h5>
            <p class="card-text mt-4 clearfix">
                {{ t.grouper.author.full_name }},
                {{ t.grouper.language }} {{ t.grouper.get_format_display | lower }}.
                {% if t.grouper.date %}
                {{ t.grouper.date }}
                {% endif %}
                <a href="{% url 'person_detail' t.grouper.author.id %}"
                    class="float-right btn btn-outline-secondary btn-sm">
                    More {{ t.grouper.author.full_name }}
                </a>

            </p>
        </div>
    </div>
    {% for feature_set in grouped_features %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">
                {% commalist feature_set.list %}
                {{ item.get_feature_display }}
                {% if item.title and item.title != item.source_text.title %}
                (as <cite>{{ item.title }}</cite>)
                {% endif %}
                {% endcommalist %}
            </h5>
            {% with f=feature_set.list|first %}
            <h6 class="card-subtitle mb-2 text-muted">
                by
                {% commalist f.persons.all %}
                <a href="{% url 'person_detail' item.id %}">{{ item.full_name }}</a>
                {% endcommalist %}
            </h6>
            {% endwith %}
            {% for f in feature_set.list %}
            {% if f.feature == 'TR' %}
            <p class="card-text clearfix">
                Translated into {{ f.language }} {{f.get_format_display | lower}}.
                {% if f.partial %} This is a partial translation. {% endif %}
                {% if f.has_facing_text %} This translation includes a facing {{ f.source_text.language }} text.
                {% endif %}
                {% if f.sample_passage %}
                <a class="float-right btn btn-sm btn-outline-secondary"
                    href="{% url 'translation_compare' f.source_text.id %}?trans={{ f.id }}">
                    View Sample
                </a>
                {% endif %}
            </p>
            {% endif %}
            {% if f.description %}
            <p class="card-text">
                {{ f.description|linebreaks }}
            </p>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
<hr>
{% endfor %}

{% include "components/links_component.html" with links=volume.links.all %}

<h2 class="mt-4 clearfix">
    Published Reviews
    <div class="float-right">
        <div class="btn-group btn-group-sm" role="group" aria-label="Published review actions">
            <a class="btn btn-secondary" href="{% url 'publishedreview_list' volume.id %}">
                View all
            </a>
            {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'publishedreview_add' volume.id %}">
                Add
            </a>
            {% endif %}
        </div>
    </div>
</h2>

{% for r in publishedreviews %}
{% include "components/published_review.html" with review=r %}
{% empty %}
<p>We don't have any published reviews for this volume yet.</p>
{% endfor %}

<h2 class="mt-4 clearfix">
    User Reviews
    <div class="float-right">
        <div class="btn-group btn-group-sm" role="group" aria-label="User review actions">
            <a class="btn btn-secondary" href="{% url 'review_list' volume.id %}">
                View all</a>
            {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'review_create' volume.id %}">
                Add
            </a>
            {% endif %}
        </div>
    </div>

</h2>

{% for r in reviews %}
{% include "components/user_review.html" with review=r abbreviate=True %}
{% empty %}
<p>We don't have any user reviews for this volume yet.</p>
{% endfor %}
{% endblock %}