backend/translations/urls.py
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r"persons", views.PersonViewSet, basename="person")
router.register(r"languages", views.LanguageViewSet, basename="language")
router.register(r"texts", views.SourceTextViewSet, basename="text")
router.register(r"volumes", views.VolumeViewSet, basename="volume")
router.register(r"volume-releases", views.VolumeReleaseViewSet, basename="volume-release")
router.register(r"publishers", views.PublisherViewSet, basename="publisher")
router.register(r"series", views.SeriesViewSet, basename="series")
router.register(r"features", views.FeatureViewSet, basename="feature")
router.register(r"reviews", views.ReviewViewSet, basename="review")
router.register(
    r"published-reviews", views.PublishedReviewViewSet, basename="published-review"
)
router.register(r"links", views.LinkViewSet, basename="link")
router.register(
    r"alternate-names", views.AlternateNameViewSet, basename="alternate-name"
)


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("graphql", GraphQLView.as_view(graphiql=True)),
    path("api/graphql", csrf_exempt(GraphQLView.as_view(graphiql=False))),
    path("about/", views.AboutView.as_view(), name="about"),
    path("texts/", views.SourceTextIndexView.as_view(), name="source_text_index"),
    path("authors/", views.AuthorIndexView.as_view(), name="author_index"),
    path("translators/", views.TranslatorIndexView.as_view(), name="translator_index"),
    path(
        "texts/<int:pk>/",
        views.SourceTextDetailView.as_view(),
        name="source_text_detail",
    ),
    path(
        "texts/<int:pk>/translations/",
        views.TranslationComparisonsView.as_view(),
        name="translation_compare",
    ),
    path("persons/<int:pk>/", views.PersonDetailView.as_view(), name="person_detail"),
    path("users/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path(
        "published-reviews/<int:pk>/",
        views.PublishedReviewDetailView.as_view(),
        name="published_review_detail",
    ),
    path("volumes/<int:pk>/", views.VolumeDetailView.as_view(), name="volume_detail"),
    path(
        "volumes/<int:vol>/reviews/",
        views.ReviewIndexView.as_view(),
        name="review_list",
    ),
    path(
        "volumes/<int:vol>/published-reviews/",
        views.PublishedReviewIndexView.as_view(),
        name="publishedreview_list",
    ),
    path(
        "volumes/<int:vol>/published-reviews/add/",
        views.PublishedReviewLWCView.as_view(),
        name="publishedreview_add",
    ),
    path(
        "volumes/add/",
        views.VolumeLWCView.as_view(),
        name="volume_add",
    ),
    path(
        "volumes/<int:vol>/review/",
        views.ReviewCreateView.as_view(),
        name="review_create",
    ),
    path(
        "reviews/<int:pk>/",
        views.UserReviewDetailView.as_view(),
        name="user_review_detail",
    ),
    path(
        "reviews/<int:pk>/update/",
        views.ReviewUpdateView.as_view(),
        name="review_update",
    ),
    path(
        "reviews/<int:pk>/delete/",
        views.ReviewDeleteView.as_view(),
        name="review_delete",
    ),
    path(
        "publishers/<int:pk>/",
        views.PublisherDetailView.as_view(),
        name="publisher_detail",
    ),
    path("series/<int:pk>/", views.SeriesDetailView.as_view(), name="series_detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("submit/", views.UserSubmissionCreateView.as_view(), name="submit"),
    path("api/", include(router.urls)),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("translations.urls")),
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/translations/models.py
import urllib.parse

import requests
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from config import settings

FORMAT_CHOICES = [("PR", "Prose"), ("VR", "Verse")]


class AuthorNameMixin:
    def author_string(self):
        authors = list(self.persons.all())
        if len(authors) < 3:
            return " and ".join(str(a) for a in authors)
        else:
            first = ", ".join(str(a) for a in authors[:-1])
            last = str(authors[-1])
            return f"{first}, and {last}"


class UserCreatedMixin(models.Model):
    class Meta:
        abstract = True

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True
    )
    date_created = models.DateTimeField(auto_now_add=True)


class UserCreatedApprovalMixin(UserCreatedMixin):
    class Meta:
        abstract = True

    approved = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.user and self.user.is_superuser:
            self.approved = True

        super().save(*args, **kwargs)


class Link(models.Model):
    class Meta:
        ordering = ["resource_type"]

    RESOURCE_TYPE_CHOICES = [
        ("CO", "Get a Copy"),
        ("FT", "Full Text"),
        ("WS", "Website"),
        ("BO", "Bio"),
        ("RS", "Resources"),
    ]

    parent_relationship = "content_object"

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    link = models.URLField()
    source = models.CharField(max_length=255)
    resource_type = models.TextField(choices=RESOURCE_TYPE_CHOICES)

    def __str__(self):
        return f"Link {self.link}"


class AlternateName(models.Model):
    ALTERNATE_NAME_TYPE_CHOICES = [
        ("OR", "Original Language Name"),
        ("TL", "Transliterated Original Language Name"),
        ("TR", "Alternate Name Translation"),
        ("NM", "Alternate Name"),
    ]
    parent_relationship = "content_object"

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    name = models.CharField(max_length=255, blank=False, null=False)
    alternate_name_type = models.CharField(
        max_length=2, choices=ALTERNATE_NAME_TYPE_CHOICES
    )

    def __str__(self):
        return f"Alternate Name {self.name}"


class Language(models.Model):
    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Person(UserCreatedApprovalMixin):
    class Meta:
        ordering = ["sort_name"]

    first_name = models.CharField(max_length=255, blank=True)
    middle_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    sole_name = models.CharField(max_length=255, blank=True)
    sort_name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True)
    links = GenericRelation(Link)
    alternate_names = GenericRelation(AlternateName)

    def save(self, *args, **kwargs):
        self.sort_name = (
            self.sole_name
            if self.sole_name
            else f"{self.last_name}, {self.first_name} {self.middle_name}".strip()
        )
        super().save(*args, **kwargs)

    def clean(self):
        if (not self.sole_name and (not self.first_name or not self.last_name)) or (
            self.sole_name and (self.first_name or self.middle_name or self.last_name)
        ):
            raise ValidationError(
                _(
                    "Populate either the Sole Name or the First Name"
                    "and Last Name fields"
                )
            )

    def full_name(self):
        if self.sole_name:
            return self.sole_name

        if self.middle_name:
            return f"{self.first_name} {self.middle_name} {self.last_name}"

        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.sort_name

    def translation_count(self):
        return self.features.filter(feature="TR").count()

    def get_absolute_url(self):
        return reverse("person_detail", args=[str(self.id)])


class SourceTextManager(models.Manager["SourceText"]):
    def get_queryset(self) -> models.QuerySet["SourceText"]:
        return super().get_queryset().select_related("author")


class SourceText(UserCreatedApprovalMixin):
    class Meta:
        ordering = ["title"]

    objects = SourceTextManager()

    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        Person, related_name="source_texts", on_delete=models.PROTECT
    )
    language = models.ForeignKey(
        Language, related_name="source_texts", on_delete=models.PROTECT
    )
    format = models.TextField(choices=FORMAT_CHOICES)
    date = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)

    # Sample passage data
    sample_passage = models.TextField(blank=True)
    sample_passage_spec = models.CharField(max_length=255, blank=True)
    sample_passage_source = models.CharField(max_length=255, blank=True)
    sample_passage_source_link = models.URLField(blank=True, null=True)
    sample_passage_license = models.CharField(max_length=255, blank=True)
    sample_passage_license_link = models.URLField(blank=True, null=True)

    # Coverage tracking
    coverage = models.TextField(blank=True)
    coverage_date = models.DateField(blank=True, null=True)

    # Generic relations
    links = GenericRelation(Link)
    alternate_names = GenericRelation(AlternateName)

    def display_name(self):
        return f"{self.title} ({self.author})"

    def __str__(self):
        return self.display_name()

    def get_absolute_url(self):
        return reverse("source_text_detail", args=[str(self.id)])

    def get_original_language_title(self):
        olt = self.alternate_names.filter(alternate_name_type="OR")

        if olt:
            return olt[0].name


class Publisher(UserCreatedApprovalMixin):
    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    links = GenericRelation(Link)

    def __str__(self):
        return self.name


class Series(UserCreatedApprovalMixin):
    class Meta:
        verbose_name_plural = "series"
        ordering = ["name"]

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class VolumeManager(models.Manager["Volume"]):
    def get_queryset(self) -> models.QuerySet["Volume"]:
        return super().get_queryset().prefetch_related("features", "series", "publisher", "features__source_text", "features__language", "features__persons")


class Volume(UserCreatedApprovalMixin):
    class Meta:
        ordering = ["title"]

    objects = VolumeManager()

    title = models.CharField(max_length=255)
    published_date = models.DateField(blank=True)
    publisher = models.ForeignKey(
        Publisher, related_name="volumes", on_delete=models.PROTECT
    )
    series = models.ForeignKey(
        Series, related_name="volumes", on_delete=models.PROTECT, null=True, blank=True
    )
    isbn = models.CharField(max_length=32, blank=True)
    oclc_number = models.CharField(max_length=32, blank=True)
    links = GenericRelation(Link)
    description = models.TextField(blank=True)

    # Additional features

    feature_maps = models.BooleanField(default=False)
    feature_index = models.BooleanField(default=False)
    feature_bibliography = models.BooleanField(default=False)
    feature_glossary = models.BooleanField(default=False)

    def __str__(self):
        if self.published_date:
            return f"{self.title} ({self.publisher}, {self.published_date.year})"

        return f"{self.title} ({self.publisher})"

    def get_general_features(self):
        return Feature.objects.filter(volume=self, source_text=None)

    def translations(self):
        return self.features.filter(feature="TR")

    def get_absolute_url(self):
        return reverse("volume_detail", args=[str(self.id)])

    def oclc_link(self):
        if self.oclc_number:
            escaped = urllib.parse.quote(self.oclc_number)
            return f"https://www.worldcat.org/oclc/{escaped}"
        elif self.isbn:
            escaped = urllib.parse.quote(self.isbn)
            return (
                f"https://www.worldcat.org/search?q=bn%3A{escaped}"
                "&qt=advanced&dblist=638"
            )

    def bookshop_link(self):
        if self.isbn:
            escaped = urllib.parse.quote(self.isbn)
            return f"https://bookshop.org/a/15029/{escaped}"

    def update_automatic_links(self):
        links = self.links.all()[:]

        # Do we need an OCLC link?
        url = self.oclc_link()
        if (
            url
            and not any(
                this_link.link.startswith("https://www.worldcat.org")
                for this_link in links
            )
            and requests.head(url).status_code < 300
        ):
            oclc = Link(
                content_object=self,
                link=self.oclc_link(),
                source="Worldcat Libraries",
                resource_type="CO",
            )
            oclc.save()

        url = self.bookshop_link()
        if (
            url
            and not any(
                this_link.link.startswith("https://bookshop.org") for this_link in links
            )
            and requests.head(url).status_code < 300
        ):
            bookshop = Link(

backend/translations/templates/components/links_component.html
<h2 class="mt-4">Links</h2>
{% if links %}
<div class="card mb-3">
    {% include "components/links_list_component.html" with links=links %}
</div>
{% else %}
<p>There are no links available.</p>
{% endif %}

backend/translations/templates/components/links_list_component.html
<ul class="list-group list-group-flush">
    {% for l in links %}
    <li class="list-group-item">
        <span class="badge badge-secondary">
            {{ l.get_resource_type_display }}
        </span>
        <a href="{{ l.link }}">{{ l.source }}</a>
    </li>
    {% endfor %}
</ul>

backend/translations/templates/components/pagination.html
<div class="pagination">
    <p class="text-center w-100">
        {% if page_obj.has_previous %}
        <span class="mr-4">
            <a href="?page=1">First</a> &laquo;
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </span>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <span class="ml-4">
            <a href="?page={{ page_obj.next_page_number }}">Next</a> &raquo;
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        </span>
        {% endif %}
    </p>
</div>

backend/translations/templates/components/pill.html
<span style="white-space: nowrap;">
    <span class="badge badge-secondary">{{ title }}</span> {% if link %}<a href="{{ link }}">{% endif %}<span
            class="mr-4">{{ content }}</span>{% if link %}</a>{% endif %}
</span>

backend/translations/templates/components/published_review.html
{% load comma_lists %}

<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">
            {% if review.title %} {{ review.title }} {% else %} Review {% endif %}
        </h5>
        {% if include_volume or review.volumes.count > 1 %}
        <div class="card-text mb-3">
            This review covers:
            <ul>
                {% for vol in review.volumes.all %}
                <li><a href="{% url 'volume_detail' vol.id %}">{{ vol.title }}</a>,
                    {{vol.publisher}} {% if vol.published_date %}({{vol.published_date.year}}){% endif %}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <div class="card-text">
            <p>
                by
                {% commalist review.persons.all %}
                <a href="{% url 'person_detail' item.id %}">{{ item.full_name }}</a>
                {% endcommalist %}.
                Published in {{ review.location }}.
                {% if review.published_date %} {{ review.published_date }}. {% endif %}

            </p>
        </div>
        {% include "components/links_list_component.html" with links=review.links.all %}
    </div>
</div>

backend/translations/templates/components/user_review.html
{% load comma_lists %}

<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title clearfix">
            {% if review.title %} {{ review.title }} {% else %} Review {% endif %} by
            <a href="{% url 'user_detail' review.user.id %}">{{ review.user.display_name }}</a>
            {% if review.user == request.user %}
            <div class="btn-group float-right ml-3" role="group" aria-label="Review options">
                <a class="btn btn-secondary btn-sm" href="{% url 'review_update' review.id %}">Edit</a>
                <a class="btn btn-danger btn-sm" href="{% url 'review_delete' review.id %}">Delete</a>
            </div>
            {% endif %}
        </h5>
        {% if include_volume %}
        <div class="card-text mb-3">
            Review of <a href="{% url 'volume_detail' review.volume.id %}">{{ review.volume.title }}</a>,
            {{review.volume.publisher}} {% if vol.published_date %}({{review.volume.published_date.year}}){% endif%}
        </div>
        {% endif %}
        <div class="card-text mb-3">
            {% if review.recommended %}
            {% pill "Recommended" "Yes" %}
            {% else %}
            {% pill "Recommended" "No" %}
            {% endif %}
            {% pill "Readability" review.readability_rating_string %}
            {% pill "Closeness" review.closeness_rating_string %}
        </div>
        <div class="card-text">
            {% if abbreviate %}
            {{ review.content|linebreaks|truncatewords:80 }}
            <p><a href="{% url 'user_review_detail' review.id %}">Read more</a></p>
            {% else %}
            {{ review.content|linebreaks }}
            {% endif %}
        </div>
        {% if not abbreviate %}
        <div class="card-text">
            <p>
                <a href="{% url 'user_review_detail' review.id %}">Permalink</a>
            </p>
        </div>
        {% endif %}
    </div>
</div>